--
-- PostgreSQL database dump
--

\restrict TzChhtrFvYnGWdbKbjehZCF1iDwezHJcsteqg6AYHznSa4SaayEWueb9N6NYBKI

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-25 03:07:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24578)
-- Name: agency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agency (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(255),
    country character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    current_balance numeric(15,2),
    daily_limit numeric(15,2),
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.agency OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24577)
-- Name: agency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24589)
-- Name: agent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agent (
    active boolean NOT NULL,
    id bigint NOT NULL,
    agency_id bigint NOT NULL
);


ALTER TABLE public.agent OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24598)
-- Name: cash_registers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cash_registers (
    id bigint NOT NULL,
    balance numeric(18,2) NOT NULL,
    closedat timestamp(6) without time zone,
    open boolean NOT NULL,
    openedat timestamp(6) without time zone,
    agency_id bigint NOT NULL,
    agent_id bigint NOT NULL
);


ALTER TABLE public.cash_registers OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24597)
-- Name: cash_registers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cash_registers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_registers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24609)
-- Name: corridor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corridor (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    destination_country character varying(3) NOT NULL,
    source_country character varying(3) NOT NULL,
    updated_at timestamp(6) without time zone,
    destination_currency_id bigint NOT NULL,
    source_currency_id bigint NOT NULL
);


ALTER TABLE public.corridor OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24608)
-- Name: corridor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.corridor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.corridor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24622)
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(3) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    exchange_rate numeric(18,6) NOT NULL,
    last_updated timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    symbol character varying(10) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24621)
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 24635)
-- Name: currency_rate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency_rate (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    pair character varying(10) NOT NULL,
    rate numeric(18,6) NOT NULL,
    source character varying(50)
);


ALTER TABLE public.currency_rate OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24634)
-- Name: currency_rate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency_rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 24646)
-- Name: fee_grid; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fee_grid (
    id bigint NOT NULL,
    active boolean NOT NULL,
    agency_share numeric(5,2) NOT NULL,
    central_share numeric(5,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fixed_fee numeric(10,2) NOT NULL,
    max_amount numeric(15,2) NOT NULL,
    min_amount numeric(15,2) NOT NULL,
    percentage_fee numeric(5,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    corridor_id bigint NOT NULL
);


ALTER TABLE public.fee_grid OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24645)
-- Name: fee_grid_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fee_grid ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_grid_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 24662)
-- Name: journal_audit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.journal_audit (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    details text,
    entity_id bigint,
    entity_type character varying(255),
    performed_at timestamp(6) without time zone NOT NULL,
    performed_by character varying(255) NOT NULL
);


ALTER TABLE public.journal_audit OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24661)
-- Name: journal_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.journal_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 24674)
-- Name: transfers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transfers (
    id bigint NOT NULL,
    amount numeric(18,2) NOT NULL,
    convertedamount numeric(18,2),
    createdat timestamp(6) without time zone,
    currency character varying(255),
    recipientcountry character varying(255),
    recipientname character varying(255),
    recipientphone character varying(255),
    sendercountry character varying(255),
    status character varying(255) NOT NULL,
    targetcurrency character varying(255),
    transfercode character varying(255) NOT NULL,
    updatedat timestamp(6) without time zone,
    agency_id bigint,
    sender_id bigint NOT NULL,
    CONSTRAINT transfers_currency_check CHECK (((currency)::text = ANY ((ARRAY['XOF'::character varying, 'EUR'::character varying, 'USD'::character varying, 'GBP'::character varying, 'MAD'::character varying, 'GNF'::character varying, 'XAF'::character varying])::text[]))),
    CONSTRAINT transfers_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VALIDATED'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[]))),
    CONSTRAINT transfers_targetcurrency_check CHECK (((targetcurrency)::text = ANY ((ARRAY['XOF'::character varying, 'EUR'::character varying, 'USD'::character varying, 'GBP'::character varying, 'MAD'::character varying, 'GNF'::character varying, 'XAF'::character varying])::text[])))
);


ALTER TABLE public.transfers OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 24673)
-- Name: transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 24690)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'AGENT'::character varying, 'CLIENT'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 24689)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5091 (class 0 OID 24578)
-- Dependencies: 220
-- Data for Name: agency; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.agency (id, active, address, country, created_at, current_balance, daily_limit, name, updated_at) FROM stdin;
\.


--
-- TOC entry 5092 (class 0 OID 24589)
-- Dependencies: 221
-- Data for Name: agent; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.agent (active, id, agency_id) FROM stdin;
\.


--
-- TOC entry 5094 (class 0 OID 24598)
-- Dependencies: 223
-- Data for Name: cash_registers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cash_registers (id, balance, closedat, open, openedat, agency_id, agent_id) FROM stdin;
\.


--
-- TOC entry 5096 (class 0 OID 24609)
-- Dependencies: 225
-- Data for Name: corridor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.corridor (id, active, created_at, destination_country, source_country, updated_at, destination_currency_id, source_currency_id) FROM stdin;
\.


--
-- TOC entry 5098 (class 0 OID 24622)
-- Dependencies: 227
-- Data for Name: currency; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.currency (id, active, code, created_at, exchange_rate, last_updated, name, symbol, updated_at) FROM stdin;
\.


--
-- TOC entry 5100 (class 0 OID 24635)
-- Dependencies: 229
-- Data for Name: currency_rate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.currency_rate (id, applied_at, created_at, pair, rate, source) FROM stdin;
\.


--
-- TOC entry 5102 (class 0 OID 24646)
-- Dependencies: 231
-- Data for Name: fee_grid; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fee_grid (id, active, agency_share, central_share, created_at, fixed_fee, max_amount, min_amount, percentage_fee, updated_at, corridor_id) FROM stdin;
\.


--
-- TOC entry 5104 (class 0 OID 24662)
-- Dependencies: 233
-- Data for Name: journal_audit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.journal_audit (id, action, details, entity_id, entity_type, performed_at, performed_by) FROM stdin;
\.


--
-- TOC entry 5106 (class 0 OID 24674)
-- Dependencies: 235
-- Data for Name: transfers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transfers (id, amount, convertedamount, createdat, currency, recipientcountry, recipientname, recipientphone, sendercountry, status, targetcurrency, transfercode, updatedat, agency_id, sender_id) FROM stdin;
\.


--
-- TOC entry 5108 (class 0 OID 24690)
-- Dependencies: 237
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, enabled, firstname, lastname, password, phone, role, updated_at, username) FROM stdin;
\.


--
-- TOC entry 5114 (class 0 OID 0)
-- Dependencies: 219
-- Name: agency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.agency_id_seq', 1, false);


--
-- TOC entry 5115 (class 0 OID 0)
-- Dependencies: 222
-- Name: cash_registers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cash_registers_id_seq', 1, false);


--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 224
-- Name: corridor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.corridor_id_seq', 1, false);


--
-- TOC entry 5117 (class 0 OID 0)
-- Dependencies: 226
-- Name: currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_id_seq', 1, false);


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 228
-- Name: currency_rate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_rate_id_seq', 1, false);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 230
-- Name: fee_grid_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fee_grid_id_seq', 1, false);


--
-- TOC entry 5120 (class 0 OID 0)
-- Dependencies: 232
-- Name: journal_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.journal_audit_id_seq', 1, false);


--
-- TOC entry 5121 (class 0 OID 0)
-- Dependencies: 234
-- Name: transfers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transfers_id_seq', 1, false);


--
-- TOC entry 5122 (class 0 OID 0)
-- Dependencies: 236
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 4905 (class 2606 OID 24588)
-- Name: agency agency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agency
    ADD CONSTRAINT agency_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 24596)
-- Name: agent agent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT agent_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 24607)
-- Name: cash_registers cash_registers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cash_registers
    ADD CONSTRAINT cash_registers_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 24620)
-- Name: corridor corridor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corridor
    ADD CONSTRAINT corridor_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 24633)
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id);


--
-- TOC entry 4919 (class 2606 OID 24644)
-- Name: currency_rate currency_rate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency_rate
    ADD CONSTRAINT currency_rate_pkey PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 24660)
-- Name: fee_grid fee_grid_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_grid
    ADD CONSTRAINT fee_grid_pkey PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 24672)
-- Name: journal_audit journal_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_audit
    ADD CONSTRAINT journal_audit_pkey PRIMARY KEY (id);


--
-- TOC entry 4925 (class 2606 OID 24688)
-- Name: transfers transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT transfers_pkey PRIMARY KEY (id);


--
-- TOC entry 4929 (class 2606 OID 24712)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4913 (class 2606 OID 24706)
-- Name: corridor uk_corridor_source_dest; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corridor
    ADD CONSTRAINT uk_corridor_source_dest UNIQUE (source_country, destination_country);


--
-- TOC entry 4917 (class 2606 OID 24708)
-- Name: currency ukh84pd2rtr12isnifnj655rkra; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT ukh84pd2rtr12isnifnj655rkra UNIQUE (code);


--
-- TOC entry 4931 (class 2606 OID 24714)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 4927 (class 2606 OID 24710)
-- Name: transfers ukrf7vbj0tb49u52aly4tpfpobb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT ukrf7vbj0tb49u52aly4tpfpobb UNIQUE (transfercode);


--
-- TOC entry 4933 (class 2606 OID 24704)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 24715)
-- Name: agent fk2karykbqlyw19a0e80gcf9ch9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT fk2karykbqlyw19a0e80gcf9ch9 FOREIGN KEY (agency_id) REFERENCES public.agency(id);


--
-- TOC entry 4936 (class 2606 OID 24730)
-- Name: cash_registers fk358e9wpy9s7l6b2g7ury5v2tw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cash_registers
    ADD CONSTRAINT fk358e9wpy9s7l6b2g7ury5v2tw FOREIGN KEY (agent_id) REFERENCES public.agent(id);


--
-- TOC entry 4938 (class 2606 OID 24735)
-- Name: corridor fk_corridor_dest_currency; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corridor
    ADD CONSTRAINT fk_corridor_dest_currency FOREIGN KEY (destination_currency_id) REFERENCES public.currency(id);


--
-- TOC entry 4939 (class 2606 OID 24740)
-- Name: corridor fk_corridor_source_currency; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corridor
    ADD CONSTRAINT fk_corridor_source_currency FOREIGN KEY (source_currency_id) REFERENCES public.currency(id);


--
-- TOC entry 4940 (class 2606 OID 24745)
-- Name: fee_grid fk_feegrid_corridor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_grid
    ADD CONSTRAINT fk_feegrid_corridor FOREIGN KEY (corridor_id) REFERENCES public.corridor(id);


--
-- TOC entry 4935 (class 2606 OID 24720)
-- Name: agent fkdhj5yjc2jy93mxoouo5rmlrn2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT fkdhj5yjc2jy93mxoouo5rmlrn2 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- TOC entry 4937 (class 2606 OID 24725)
-- Name: cash_registers fkfpv1hhdiyel3ol3sm5uiqqf4g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cash_registers
    ADD CONSTRAINT fkfpv1hhdiyel3ol3sm5uiqqf4g FOREIGN KEY (agency_id) REFERENCES public.agency(id);


--
-- TOC entry 4941 (class 2606 OID 24750)
-- Name: transfers fkgr18jttkq51wcw2dertjsb0cl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fkgr18jttkq51wcw2dertjsb0cl FOREIGN KEY (agency_id) REFERENCES public.agency(id);


--
-- TOC entry 4942 (class 2606 OID 24755)
-- Name: transfers fkpn4x20jhioy57ykp4be3jnei4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fkpn4x20jhioy57ykp4be3jnei4 FOREIGN KEY (sender_id) REFERENCES public.users(id);


-- Completed on 2026-05-25 03:07:35

--
-- PostgreSQL database dump complete
--

\unrestrict TzChhtrFvYnGWdbKbjehZCF1iDwezHJcsteqg6AYHznSa4SaayEWueb9N6NYBKI

