# Database
db.url=jdbc:postgresql://localhost:5432/okane_transfer
db.username=<db_username>
db.password=<db_password>
db.driver=org.postgresql.Driver

# Hibernate
hibernate.ddl-auto=update
hibernate.show_sql=false

# JWT (min 32 caractères)
jwt.secret=<jwt_secret_min_32_characters>
jwt.expiration=3600000
jwt.expiration.ms=3600000

# Crypto AES-256 (exactement 32 caractères)
crypto.aes.secret=<aes_secret_exactly_32_characters>

# SpringDoc
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
